---
abstract: 'Provide regexes for profanity in Austrian German'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common-AT-Profanity
provides:
  Regexp::Common::AT::Profanity:
    file: lib/Regexp/Common/AT/Profanity.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  HTML::Entities: 0
  Regexp::Assemble: 0
  Regexp::Common: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Regexp-Common-AT-Profanity
  homepage: http://search.cpan.org/dist/Regexp-Common-AT-Profanity/
  repository: http://github.com/hanekomu/Regexp-Common-AT-Profanity
version: 1.100860
